config/routes.rb
PLReviews::Application.routes.draw do
  resources :breweries

  get 'log_in', to: 'sessions#new', as: 'log_in'
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'sign_up', to: 'users#new', as: 'sign_up'
  get 'beers/:id/open', to: 'beers#open', as: 'open_beer'
  root to: 'beers#index'
  resources :activities, only: [:index, :show]
  resources :beers
  resources :breweries do
    resources :beers, only: [:index]
  end
  resources :reviews, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery, counter_cache: true
  has_many :reviews, dependent: :destroy
  has_many :reviewers, through: :reviews, class_name: 'User', source: :user
  has_many :beer_opened_activities, dependent: :destroy
  has_many :beer_added_activities, dependent: :destroy

  validates_presence_of :name
  validates_presence_of :brewery
  validates_presence_of :inventory
  validates_numericality_of :inventory, only_integer: true, greater_than_or_equal_to: 0

  def average_rating
    reviews.average(:rating).round(1) if reviews.any?
  end
end

app/models/beer_form.rb
class BeerForm
  include ActiveModel::Model
  attr_accessor :name, :brewery_id, :inventory, :thumbnail

  validates_presence_of :name
  validates_presence_of :brewery_id
  validates_presence_of :inventory
  validates_numericality_of :inventory, only_integer: true, greater_than_or_equal_to: 0
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  skip_before_action :require_authentication, only: [:index, :show]
  before_action :set_beer, only: [:show, :edit, :update, :destroy, :open]
  before_action :set_breweries, only: [:new, :edit, :create, :update]
  after_filter :set_access_control, only: [:index]
  helper_method :sort_column, :sort_direction
  skip_before_filter :verify_authenticity_token

  # GET /beers
  def index
    if params[:brewery_id]
      @brewery = Brewery.find(params[:brewery_id])
      beers = Beer.where(brewery: @brewery)
    else
      beers = Beer.all
    end

    if params[:in_stock] == '1'
      @in_stock = '1'
      beers.where!('inventory > 0')
    end

    @beers = beers.order(sort_column + ' ' + sort_direction).page(params[:page])
    respond_with @beers, meta: {total_count: beers.length, page: params[:page] || 1}
  end

  # GET /beers/1
  def show
    @review = Review.new
    respond_with @beer
  end

  # GET /beers/new
  def new
    @beer = Beer.new
    @beer_form = BeerForm.new
  end

  # GET /beers/1/edit
  def edit
    @beer_form = BeerForm.new({
                                  name: @beer.name,
                                  brewery_id: @beer.brewery_id,
                                  inventory: @beer.inventory
                              })
  end

  # POST /beers
  def create
    @beer_form = BeerForm.new(beer_form_params)


    respond_to do | format|
      format.html do
        if @beer_form.valid?
          @beer = Beer.new({
                               name: @beer_form.name,
                               brewery_id: @beer_form.brewery_id,
                               inventory: @beer_form.inventory
                           })
          @beer.beer_added_activities << BeerAddedActivity.new(beer: @beer, user: current_user)

          if @beer.save
            redirect_to @beer, notice: 'Beer was successfully created.'
          else
            @beer = Beer.new
            render action: :new
          end
        else
          @beer = Beer.new
          render action: :new
        end
      end
      format.json do
        if @beer_form.valid?
          @beer = Beer.new({
                               name: @beer_form.name,
                               brewery_id: @beer_form.brewery_id,
                               inventory: @beer_form.inventory
                           })
          @beer.beer_added_activities << BeerAddedActivity.new(beer: @beer, user: current_user)

          if @beer.save
            render json: @beer
          else
            render nothing: true, status: 500
          end
        else
          render nothing: true, status: 500
        end
      end
    end
  end

  # PATCH/PUT /beers/1
  def update
    @beer_form = BeerForm.new(beer_form_params)
    if @beer_form.valid?

      @beer.name = @beer_form.name
      @beer.brewery_id = @beer_form.brewery_id
      @beer.inventory = @beer_form.inventory

      if @beer.save
        redirect_to @beer, notice: 'Beer was successfully updated.' and return
      end
    end
    render action: :edit
  end

  # DELETE /beers/1
  def destroy
    @beer.destroy
    redirect_to beers_url
  end

  # GET OPEN /beer/1/open
  def open
    if @beer.inventory > 0
      @beer.decrement(:inventory)
      @beer.beer_opened_activities << BeerOpenedActivity.new(user: current_user)

      if @beer.save
        flash.notice = "A bottle of #{@beer.name} was successfully opened."
      else
        flash.alert = "Failed to open a bottle of #{@beer.name}."
      end
    else
      flash.alert = "No bottles of #{@beer.name} left to open."
    end

    @review = Review.new
    redirect_to @beer
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_beer
    @beer = Beer.find(params[:id])
  end

  def set_breweries
    @breweries = Brewery.order(:name)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_form_params
    params.require(:beer_form).permit(:name, :brewery_id, :inventory, :thumbnail)
  end

  def sort_column
    Beer.column_names.include?(params[:sort]) ? params[:sort] : 'name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/admin/beers/_form.html.erb
<div class='new-form'>
    <%
       if @beer.persisted?
         form_url = beer_url(@beer)
         form_method = 'PUT'
         submit_text = 'Update Beer'
       else
         form_url = beers_url
         form_method = 'POST'
         submit_text = 'Add Beer'
       end
    %>
    <%= form_for(@beer_form, url: form_url, method: form_method, html: {class: 'form-horizontal'}) do |f| %>
        <% if @beer_form.errors.any? %>
            <div class='panel panel-danger'>
                <div class='panel-heading'>
                    <h4 class='panel-title'><%= pluralize(@beer_form.errors.count, 'error') %> prohibited this beer from
                        being saved</h4>
                </div>
                <div class='panel-body'>
                    <ul>
                        <% @beer_form.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>

        <div class='form-group'>
            <%= f.label :name, class: 'col-sm-3 control-label' %>
            <div class='col-sm-8'>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
        </div>
        <div class='form-group'>
            <%= f.label :brewery, class: 'col-sm-3 control-label' %>
            <div class='col-sm-8'>
                <% if @breweries.length > 0 %>
                    <%= f.select :brewery_id, options_from_collection_for_select(@breweries, :id, :name, (@beer.brewery) ? @beer.brewery.id : nil), class: 'form-control' %>
                    or
                <% end %>
                <p class="form-control-static">
                    <%= link_to 'Add a new brewery', new_brewery_path %>
                </p>
            </div>
        </div>
        <div class='form-group'>
            <%= f.label :inventory_count, "Inventory Count", class: 'col-sm-3 control-label' %>
            <div class='col-sm-8'>
                <%= f.number_field :inventory, class: 'form-control', value: (@beer_form.inventory || 0) %>
            </div>
        </div>
        <div class='form-group'>
            <%= f.label :thumbnail, 'Image', class: 'col-sm-3 control-label' %>
            <div class='col-sm-6'>
                <%= f.file_field :thumbnail, class: 'form-control', accept: 'image/png,image/jpeg' %>
            </div>
        </div>

        <div class='form-group'>
            <div class='col-sm-offset-3 col-sm-8'>
                <%= f.submit submit_text, class: 'btn btn-primary' %>
            </div>
        </div>
    <% end %>
</div>

app/views/admin/beers/_list.html.erb
<table class="table table-striped beers-list">
    <thead>
    <tr class="info">
        <th><%= sortable 'name' %></th>
        <th>Brewery</th>
        <th>Average Rating</th>
        <th>Inventory</th>
        <% if current_user %>
            <th></th>
        <% end %>
    </tr>
    </thead>

    <tbody>
    <% @beers.each do |beer| %>
        <tr>
            <td><%= link_to beer.name, beer %></td>
            <td><%= link_to beer.brewery.name, beer.brewery %></td>
            <td><%= beer.average_rating || 'Not Rated' %></td>
            <td><%= beer.inventory %></td>
            <% if current_user %>
                <td>
                    <%= link_to beer, method: :delete, data: {confirm: 'Are you sure?'},
                                class: 'btn btn-danger  btn-xs pull-right', style: 'margin-left: 5px' do %>
                        <span class='glyphicon glyphicon-remove'></span>
                    <% end %>
                    <%= link_to edit_beer_path(beer), class: 'btn btn-default btn-xs pull-right', style: 'margin-left: 5px' do %>
                        <span class='glyphicon glyphicon-pencil'></span>
                    <% end %>
                    <% if beer.inventory != 0 %>
                        <%= link_to 'Open Bottle', open_beer_path(beer), class: 'btn btn-primary btn-xs pull-right' %>
                    <% end %>

                </td>
            <% end %>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate @beers %>
<br>

app/views/admin/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

app/views/admin/beers/index.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>
            <%= (!@in_stock ? "All" : "") %> <%= "#{@brewery.name} " if @brewery %> Beers <%= (@in_stock ? "in stock" : "") %>

            <%
               if @brewery
                 all_path = brewery_beers_path(@brewery)
                 in_stock_path = brewery_beers_path(@brewery, in_stock: '1')
               else
                 all_path = beers_path
                 in_stock_path = beers_path(in_stock: '1')
               end
            %>

            <% if @in_stock %>
                <%= link_to 'View all beers', all_path, class: 'btn btn-default btn-xs' %>
            <% else %>
                <%= link_to 'View only beers in stock', in_stock_path, class: 'btn btn-default btn-xs' %>
            <% end %>

            <% if current_user %>
                <%= link_to '+ Add Beer', new_beer_path, class: 'btn btn-primary pull-right' %>
            <% end %>
        </h1>

        <%= render 'list' %>

        <br>
    </div>
</div>

app/views/admin/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

app/views/admin/beers/show.html.erb
<div class='beer-title-row'>
    <h1 class='beer-title'>
        <%= @beer.name %> 
        <small>by <%= link_to @beer.brewery.name, @beer.brewery %></small>
        <% if current_user %>
            <%= link_to edit_beer_path(@beer), class: 'btn btn-default btn-xs' do %>
                <span class='glyphicon glyphicon-pencil'></span> Edit Beer
            <% end %>
            <% if @beer.inventory > 0 %>
                <%= link_to 'Open a Bottle', :open_beer, class: 'btn btn-primary btn-xs' %>
            <% end %>
        <% end %>
    </h1>
</div>

<hr>
<div class="beer-info">
    <span class="label label-default">Inventory Count: <%= @beer.inventory %></span>
    <span class="label label-success">Average Rating: <%= @beer.average_rating || 'Not Rated' %></span>
</div>
<hr>

<div class="row">
    <div class='col-sm-12'>
        <% if @beer.reviews.length > 0 %>
            <h4><strong>Reviews</strong></h4>
            <%= render @beer.reviews %>
        <% end %>

        <% if current_user %>
            <%= render 'reviews/form' %>
        <% end %>
    </div>
</div>

<div class="modal fade" id="beer-image-modal" tabindex="-1" role="dialog" aria-labelledby="beer-image-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body text-center">
            <%= image_tag @beer.image_url || 'placeholder.png' %>
          </div>
        </div>
    </div>
</div>